version: '3.9'
services:
  db:
    image: mysql:latest
    volumes:
      - ./tmp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'asd123'
    ports:
      - '3306:3306'
    command: [mysqld, --default-authentication-plugin=mysql_native_password]
  wallet:
    build:
      context: .
    volumes:
      - /node_modules
      - /tmp
      - .:/wallet:cached
    tty: true
    stdin_open: true
    command: 'npm start'
    ports:
      - '3000:3000'
    depends_on:
      - db
  wallet-ui:
    image: creation-mono_wallet
    tty: true
    stdin_open: true
    volumes:
      - /node_modules
      - /tmp
      - .:/wallet:cached
    command: 'npx nx run frontend:serve'
    ports:
      - '4200:4200'
    depends_on:
      - wallet
