version: 2.1
orbs:
  nx: nrwl/nx@1.0.0
  heroku: circleci/heroku@1.2.6
jobs:
  main:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel --max-parallel=3
      # - run: npx nx affected --base=$NX_BASE --target=test --parallel --max-parallel=2
      - run: npm run deploy-migration
  pr:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: npm install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel --max-parallel=3
      # - run: npx nx affected --base=$NX_BASE --target=test --parallel --max-parallel=2
workflows:
  # build:
  #   jobs:
  #     - main:
  #         filters:
  #           branches:
  #             only: main
  #     - pr:
  #         filters:
  #           branches:
  #             ignore: main
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
